services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: supplycart
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=kyoto_supplycart
      - DB_USERNAME=randhawa
      - DB_PASSWORD=raj0176698168
    volumes:
      - .:/var/www/html
      - ./node_modules:/app/node_modules
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - kyoto
